config/routes.rb
Rails.application.routes.draw do
  get 'statistics/index'

  get 'sessions/new'

  get 'users/new'

  get "home" => 'static_pages#home'
  get "help" => 'static_pages#help'
  get "about" =>  'static_pages#about'

  get "signup" => "users#new"
  post "signup" => "users#create"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "activities" => "static_pages#home"

  root "static_pages#home"

  resources :users
  resources :activities,          only: [:create, :destroy, :edit, :update, :show]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user

  validates :date, presence: true
  validates :activity, presence: true
  validates :minutes, presence: true
  # default_scope -> { order(date: :desc) }
  validates :user_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :activities, dependent: :destroy
  accepts_nested_attributes_for :activities

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  def index
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = current_user.activities.build(activity_params)

    if @activity.save
      flash[:success] = "Activity created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def update
    activity = Activity.find(params[:id])
    activity.update(activity_params)
    redirect_to activities_path
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def destroy
    @activity.destroy
    flash[:success] = "Activity deleted"
    redirect_to request.referrer || root_url
  end

  private

    def activity_params
      params.require(:activity).permit(:comments, :date, :activity, :minutes)
    end

    def correct_user
      @activity = current_user.activities.find_by(id: params[:id])
      redirect_to root_url if @activity.nil?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render html: "hello, world"
  end

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end

  private

    # Confirms a logged-in user.
    # def logged_in_user
    #   unless logged_in?
    #     store_location
    #     flash[:danger] = "Please log in."
    #     redirect_to login_url
    #   end
    # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @activity = current_user.activities.build if logged_in?
    @show = current_user.activities.all if logged_in?
  end

  def help
  end

  def about
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    # @activities = Activity.find(4)
    # @activity = current_user.activities.find_by(id: params[:id])
    @activity = current_user.activities.all
    @get_activity = current_user.activities.order(activity: :desc)
    @users = User.all

    respond_to do |format|
      format.html
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  wrap_parameters :user, include: [:name, :email, :password, :password_confirmation]
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "welcome"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_activity.html.erb
<br>
<li class="display-font" id="activity-<%= activity.id %>">
  <span class="activity display-font"><%= activity.activity %> ||</span>
  <span class="minutes display-font"><%= activity.minutes %> minutes ||</span>
  <span class="minutes display-font"><%= activity.comments %> ||</span>
  <span class="timestamp display-font">
    Workout was <%= time_ago_in_words(activity.date) %> ago.
      <%= link_to "delete", activity, method: :delete,
                                       data: { confirm: "You sure?" } %>
      <a href="/activities/<%=activity.id%>/edit">edit</a>
  </span>
</li>

app/views/activities/edit.html.erb
<div class="">
  <%= form_for(@activity) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field edit-activity">
      <h1>This is the edit form</h1>
      <%= f.text_area :date, placeholder: "@activity.date" %>
      <%= f.text_area :activity, placeholder: "@activity.activity" %>
      <%= f.text_area :comments, placeholder: "@activity.comment" %>
      <%= f.text_area :minutes, placeholder: "@activity.minutes" %>
      <br>
      <%= f.submit "Post", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/activities/index.html.erb
<h1>Statistics#index</h1>
<p>Find me in app/views/statistics/index.html.erb</p>

<%= @activity.all %>
<p>hi</p>

app/views/activities/show.html.erb
<%= @activity.activity %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Designed and built in Seattle, WA.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><a href="http://lifeonthereg.com">Contact the builder...</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">

  <h1 id="my-logo">Yes, I work out. </h1>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-links"><%= link_to "Home", root_path %></li>
      <li class="nav-links"><%= link_to "Help", help_path %></li>
      <% if logged_in? %>
        <li class="nav-links"><%= link_to "Log out", logout_path, method: :delete %></li>
      <% else %>
        <li class="nav-links"><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YesIStillWorkout</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Oxygen" rel="stylesheet">
  </head>

  <body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <!-- <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> -->
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_activity_form.html.erb
<%= form_for(@activity) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field" id="myList">
    <%= f.text_area :date, placeholder: "Add date (yyyy-mm-dd)" %> <br>
    <%= f.text_area :activity, placeholder: "Activity" %>
    <%= f.text_area :minutes, placeholder: "Minutes" %>
    <%= f.text_area :comments, placeholder: "Add comment" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view workouts", current_user %></span>
<span><a href="/statistics/index">view analytics</a></span>
<span><%= pluralize(current_user.activities.count, "activity") %></span>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Working on this new project!</p>

app/views/static_pages/help.html.erb
<h1>Welcome to Yes, I work out.</h1>
<h3> Log your workout activity and the duration. View a graphical breakdown based on time/day. </h3>

<h4>Lorem ipsum</h4>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <div id="activity-display" class="col-md-8">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <br>
      <section class="activity_form">
        <%= render 'shared/activity_form' %>
      </section>
    </div>
  </div>
  <br>
  <h2 style="text-align: center">Activity breakdown</h2>
  <%= pie_chart @show.group(:activity).sum(:minutes) %>

<% else %>
  <div class="center jumbotron">
    <div id="jumbo-content">
      <h1>Yes, I work out.</h1>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary "%>
    </div>
  </div>

<% end %>

app/views/statistics/index.html.erb
<h1>Statistics</h1>
<h2>Select individual activities to view</h2>

<% act = [] %>
<!-- this is only to get the different activities -->
<% @get_activity.each do |a| %>
  <!-- get all the activities and put into act array -->
  <% if act.empty? %>
    <%act.push(a.activity)%>
    <input id="<%=a.activity%>" type="checkbox" name="graphs" value="<%=a.activity%>" onclick=toggleGraph(this.value)><%=a.activity%>
  <% elsif a.activity != act[-1] %>
     <% act.push(a.activity) %>
     <input id="<%=a.activity%>" type="checkbox" name="graphs" value="<%=a.activity%>" onclick=toggleGraph(this.value)><%=a.activity%>
  <% end %>
  <!-- <%= a.activity %> -->
  <!-- <%= a.minutes %> -->
<% end %>

<!-- <%= act %> -->
<!-- //render a graph for each of the elements of the act arr -->

<h1>Total minutes of activity by day</h1>
<%= line_chart @activity.group(:date).sum(:minutes) %>

<% act.each do |i| %>
  <div id="<%=i%>-title" style="display: none ">
    <h1>Total minutes of <%= i %> per day</h1>
    <%= line_chart @activity.where("activity = '#{i}'").group(:date).sum(:minutes) %>
  </div>
<% end %>
<!-- <%= line_chart User.group_by_day(:created_at).count %> -->

<script>
function toggleGraph(val) {
  var isChecked = $("#" + val).is(":checked");

  if (isChecked) {
    $("#" + val + "-title").show();
  } else {
    $("#" + val + "-title").hide();
  }
}
</script>












<!-- Bottom -->

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 login-form">
    <%= form_for(@user, url: signup_path) do |f| %>
      <h1>Sign up</h1>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

<div class="col-md-8 header-font" id="activity-display">
  <% if @user.activities.any? %>
    <h3>Activities (<%= @user.activities.count %>)</h3>
    <a href="/statistics/index">view analytics</a>
    <ol class="activities">
      <%= render @activities %>
    </ol>
    <%= will_paginate @activities %>
  <% end %>
</div>